# Revision  information
# |----------------------------------------------------------------------------|
# | Ver |   Date   |  Releaser  | Comments                                     |
# |----------------------------------------------------------------------------|
# | 0.1 | 20170904 | Nick.Hu | Initial version                                 |
# |----------------------------------------------------------------------------|
# |----------------------------------------------
# |Bootloader.mtb		        10000000	0.5
# |CH2201    		            10000800
# |----------------------------------------------

set $psr=0xc0000000
set *0x4000204c=0x1f

##Load mtb
download ihex verify=yes ./utilities/generated/hexs/mtb.hex

##Load boot
download ihex verify=yes ./utilities/generated/hexs/boot.hex
